apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkusddsf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkusddsf
  template:
    metadata:
      labels:
        app: mkusddsf
    spec:
      containers:
      - image: okteto.dev/mkusddsf:latest
        name: mkusddsf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "60bc766f-e19e-43cc-b0ed-5c4403ba0ad6"
        - name: Vless_Path
          value: "/vlswaGu23we"
        - name: Vmess_UUID
          value: "60bc766f-e19e-43cc-b0ed-5c4403ba0ad6"
        - name: Vmess_Path
          value: "/vmsjifoeo3aw"
        - name: Share_Path
          value: "/v2link"
